
language: r

# GLOBAL

cache: packages
os: linux
dist: bionic

git:
  depth: false

# force all warning to be errros
warnings_are_errors: true

# deactivate pandoc
# pandoc: false

# run BiocCheck
bioc_check: true

# MATRIX: R version x env
# env : _R_CHECK_FORCE_SUGGESTS_=false

r: 
  - release
  - devel
  # - bioc-release
  # - bioc-devel

env:
  - ES_VERSION=6.8.9 R_COV=true
  - ES_VERSION=7.5.2 R_COV=true
  - ES_VERSION=7.8.1 R_COV=true
  - ES_VERSION=7.9.1 R_COV=true

# PROCESS

services:
  - docker

before_install:
  - Rscript --version
  - tlmgr install index
  - docker --version
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:$ES_VERSION
  - CID=$(docker run -d -p 9200:9200 --name "elasticsearch" -e "discovery.type=single-node" -e "transport.host=127.0.0.1" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:$ES_VERSION)

r_github_packages:
  - r-lib/covr

r_packages:
  - rmarkdown

# # options
# bioc_packages:
#   - rtracklayer
#   - Rsamtools
#   - Biostrings

# call port=9200 (default) and endpoint based on init ipaddress
before_script:
  - export KIBIOR_BUILD_ES_PORT=9200
  - export KIBIOR_BUILD_ES_ENDPOINT=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CID)
  - curl -X GET "$KIBIOR_BUILD_ES_ENDPOINT:$KIBIOR_BUILD_ES_PORT/_cluster/health?pretty"
  - wget https://raw.githubusercontent.com/Bioconductor/packagebuilder/master/check.Renviron -P /tmp
  - export R_CHECK_ENVIRON=/tmp/check.Renviron

# script call
# https://docs.travis-ci.com/user/languages/r/#customizing-the-travis-build-steps

after_success:
  - if [[ "${R_COV}" ]]; then Rscript -e 'covr::codecov(type="all")'; fi

## NOTIF

notifications:
  email:
    on_success: never
    on_failure: never